### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by sumansahoo1** [tonmoycoder/Internshala-Quiz-Answers-All-Level#1]
level 2 ques 7 answer also include -  Any job/internship he may have done in past

**Comment by sumansahoo1** [comment]
level 5 
When responding to the employer over chat, you should- 
[x] Make sure you respond politely
[] Use as many emojis as possible to make the conversation funny.
[x]Make sure that you do not use chat language (u instead of you, k instead of ok etc.)
[]Respond like you are talking to your friend
[x]Message in a professional way with proper salutations, punctuation marks, etc.

**Comment by tonmoycoder** [comment]
I've modified the response for level 2 question 7, but I can't identify any mistakes in level 5. I believe the answer provided for level 5 is accurate.
